// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAnIfKuQxRCT19dTF3poFu4EX3i0AFM2c',
    appId: '1:324618466759:web:ee14a7d0f92c5305fb55e2',
    messagingSenderId: '324618466759',
    projectId: 'diafoot-c6e57',
    authDomain: 'diafoot-c6e57.firebaseapp.com',
    storageBucket: 'diafoot-c6e57.firebasestorage.app',
    measurementId: 'G-QNVSSJXY0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvvQgrtXWaqQu5Y7h2Xx2hgPVu8Sv_a0',
    appId: '1:324618466759:android:2675e84dd82600acfb55e2',
    messagingSenderId: '324618466759',
    projectId: 'diafoot-c6e57',
    storageBucket: 'diafoot-c6e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGWuhNVnZT_6WU93QFi0WwaeJ2Ysgfpmg',
    appId: '1:324618466759:ios:d34836ccee69db13fb55e2',
    messagingSenderId: '324618466759',
    projectId: 'diafoot-c6e57',
    storageBucket: 'diafoot-c6e57.firebasestorage.app',
    iosBundleId: 'com.example.daifootcareNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGWuhNVnZT_6WU93QFi0WwaeJ2Ysgfpmg',
    appId: '1:324618466759:ios:d34836ccee69db13fb55e2',
    messagingSenderId: '324618466759',
    projectId: 'diafoot-c6e57',
    storageBucket: 'diafoot-c6e57.firebasestorage.app',
    iosBundleId: 'com.example.daifootcareNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAnIfKuQxRCT19dTF3poFu4EX3i0AFM2c',
    appId: '1:324618466759:web:bac2efb17e20b1c3fb55e2',
    messagingSenderId: '324618466759',
    projectId: 'diafoot-c6e57',
    authDomain: 'diafoot-c6e57.firebaseapp.com',
    storageBucket: 'diafoot-c6e57.firebasestorage.app',
    measurementId: 'G-7ZK72C76N2',
  );

}